title: Ambreen Hasan
author: Ambreen Hasan
email: nasahneerbma@gmail.com
avatar: ambreen-small.jpg
description: ambreen hasan software engineer personal blog
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://ambreen.rocks" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ambreenhasan
github_username:  ambreenhasan
instagram_username: ambreenh

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
